parameters:
  name:
    type: string
  shouldFetchOnLoad:
    type: boolean
  fetchedResourceName:
    type: string
  tests:
    type: stringArray
  styleRules:
    type: stringArray
  props:
    type: stringArray
  state:
    type: stringArray
  fetchedResourcePath:
    type: string
    
tags:
  - react
  - welcome
  - frontend
  - credo