headline: Get started with Credo
questions:
  - name:
      type: string
      prompt: To get us started, what is your name?
      subtext:  it doesn't need to be your real name, just something we can call you for the duration of this welcome
  - chosenLanguage:
      type: enum
      prompt: "Which language are you most comfortable with?"
      dependentKey: name
      enumMembers:
        - JavaScript
        - ruby
        - Python
  - mode:
      type: enum
      dependentKey: name
      prompt: "Choose a topic:"
      enumMembers:
        - examples
  - fibType:
      type: enum
      prompt: "Let's take a look at the fibonnacci function in your chosen language:"
      subtext: "Don't worry if you don't understand the options, just pick one"
      dependentKey: ready
      enumMembers:
        - O(n)
        - Recursive (and exponential)
        - Recursive (with memoization (linear))
  
templates:
  - welcome
